<?php
/* $Id$ */

// TODO: make it work with private files.

/**
 * Implementation of hook_help().
 */
function user_badges_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      // This description is shown in the listing at admin/modules.
      return t('Merit badges that administrators can assign to users.');

    case 'admin/settings/user_badges':
      return t("User badges are iconic images which can be assigned to users. They can represent accomplishments, status, or anything you'd like. These badges will show up in the user's profile, and could also be used by a theme to appear with user postings on forums, comments, or nodes. Badges can be assigned manually by an administrator by visiting a user's profile. They also can be assigned automatically by role or ecommerce purchase (if ecommerce modules are installed).");

    case 'admin/settings/user_badges/roles':
      return t("Select the badge that you'd like to associate with each role.");

    case 'admin/settings/user_badges/images':
      return t("Upload images to display as a user badge. These images can be anything you like, but it is recommended that you maintain a uniform icon size for all of your badges. Keep in mind that a user may have many badges displayed so you'll probably want to keep them as small as possible (like 16x16 pixels or smaller).");
  }
}

/**
 * Implementation of hook_perm().
 */
function user_badges_perm() {
  return array('manage badges');
}

/**
 * Implementation of hook_menu().
 */
function user_badges_menu() {
  $items = array();
  $access = user_badges_perm();
  $items['admin/user/user_badges'] = array(
    'title' => 'Badges',
    'page callback' => 'user_badges_settings_page',
    'access arguments' => $access,
  );

  $items['admin/user/user_badges/list'] = array(
    'title' => 'Edit user badges',
    'access arguments' => $access,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/user/user_badges/images'] = array(
    'title' => 'Images',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_badges_images_form'),
    'access arguments' => $access,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/user/user_badges/roles'] = array(
    'title' => 'Roles',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_badges_roles_form'),
    'access arguments' => $access,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/user/user_badges/delete'] = array(
    'title' => 'Delete badge',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_badges_delete_form'),
    'access arguments' => $access,
    'type' => MENU_CALLBACK,
  );
  $items['user/%user/badges'] = array(
    'title' => 'Badges',
    'page callback' => 'user_badges_page',
    'page arguments' => array(1),
    'access arguments' => $access,
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );

  return $items;
}

/**
 * Implementation of hook_user().
 *
 * This handles assignment of badges based on role.
 * When a role is assigned or removed, appropriate badges are added or removed.
 */
function user_badges_user($op, &$edit, &$account, $category = 'account') {
  switch ($op) {

    case 'load':
      if ($account->uid > 0) {
        $account->badges = user_badges_get_badges($account->uid);
      }
      break;

    case 'insert':
      if (is_array($account->roles)) {
        // Get the list of role badges.
        $roles = user_badges_get_roles();
        $badges = user_badges_get_badges('select');
        $message = user_access('manage badges');
        $rids = array_keys($account->roles);
        foreach ($rids as $rid) {
          // if this role has a badge
          if (key_exists($rid, $roles)) {
            // and user doesn't already have this badge
            if (!key_exists($roles[$rid], $account->badges)) {
              $success = user_badges_user_add_badge($account->uid, $roles[$rid], 'role');
              if ($success && $message) {
                drupal_set_message(t('User assigned %name badge.', array('%name' => $badges[$roles[$rid]])));
              }
            }
          }
        }
      }
      break;

    case 'update':
      if (is_array($edit['roles'])) {
        // Badges only get assigned or removed when a user's role assignments are changed.

        // Add authenticated users (code below only cares about array keys) to prevent badge deletion
        $new_roles = $edit['roles'];
        $new_roles[2] = 2;
        // Get the list of role badges.
        $roles = user_badges_get_roles();
        $badges = user_badges_get_badges('select');

        $message = user_access('manage badges');

        // What are the added roles?
        $added = array_diff(array_keys($new_roles), array_keys((array)$account->roles));
        foreach ($added as $rid) {
          // if this role has a badge
          if (key_exists($rid, $roles) && !key_exists($roles[$rid], $account->badges)) {
            $success = user_badges_user_add_badge($account->uid, $roles[$rid], 'role');
            if ($success && $message) {
              drupal_set_message(t('User assigned %name badge.', array('%name' => $badges[$roles[$rid]])));
            }
          }
        }

        // What are the removed roles?
        $removed = array_diff(array_keys((array)$account->roles), array_keys($new_roles));
        foreach ($removed as $rid) {
          // If this role has a badge and user has this badge..
          if (key_exists($rid, $roles) && key_exists($roles[$rid], $account->badges)) {
            $success = user_badges_user_remove_badge($account->uid, $roles[$rid], 'role');
            drupal_set_message(t('%name badge removed from user.', array('%name' => $badges[$roles[$rid]])));
          }
        }
      }
      break;

    case 'delete':
      db_query('DELETE FROM {user_badges_user} WHERE uid = %d', $account->uid);
      break;

    case 'view':
      $badgeimgs = array();
      foreach ($account->badges as $badge) {
        $badgeimgs[] = theme('user_badge', $badge);
      }
      if (!empty($badgeimgs)) {
        $account->content['user_badges'] = array(
          '#type' => 'user_profile_category',
          '#title' => t('Badges'),
          '#weight' => 10,
        );
        $account->content['user_badges']['badges'] = array(
          '#type' => 'user_profile_item',
          '#value' => theme('user_badge_group', $badgeimgs),
        );
      }
  }
}

/**
 * Implementation of hook_theme().
 */
function user_badges_theme() {
  $themes = array();
  $themes['user_badge'] = array(
    'arguments' => array(
      'badge' => NULL,
    ),
  );
  $themes['user_badge_group'] = array(
    'arguments' => array(
      'badgeimages' => array(),
    ),
  );
  return $themes;
}

/**
 * Define the page on user/uid/badges.
 */
function user_badges_page($account) {
  drupal_set_title(t('Edit badges for %user_name', array('%user_name' => $account->name)));

  return drupal_get_form('user_badges_page_form', $account);
}

/**
 * Form to assign badges to users.
 */
function user_badges_page_form(&$form_state, $account) {
  $form = array();

  $form['uid'] = array('#type' => 'value', '#value' => $account->uid);
  $form['badges'] = array('#tree' => TRUE);

  $badges = user_badges_get_badges('all');
  foreach ($badges as $badge) {
    $form['badges'][$badge->bid] = array(
      '#type' => 'checkbox',
      '#title' => theme('user_badge', $badge),
      '#return_value' => 1,
      '#default_value' => array_key_exists($badge->bid, $account->badges),
      '#description' => check_plain($badge->name),
    );
  }

  $form[] = array(
    '#type' => 'submit',
    '#value' => t('Save Badges'),
  );
  return $form;
}

function user_badges_page_form_submit($form, &$form_state) {
  $badges = $form_state['values']['badges'];
  $uid = $form_state['values']['uid'];
  user_badges_user_save($badges, $uid, FALSE);
}

/**
 * Assign user badges to a user
 *
 * $edit is an array containing badges array
 * $uid is the user id
 * $quiet suppresses message display
 */
function user_badges_user_save($edit, $uid, $quiet = TRUE) {
  $badges = user_badges_get_badges($uid);

  if (is_array($edit)) {
    // an array of just the checked boxes please
    $newbadges = array();
    foreach ($edit as $bid => $is_selected) {
      if ($is_selected) {
        $newbadges[] = $bid;
      }
    }

    $success = TRUE;

    // what are the added badges?
    $added = array_diff($newbadges, array_keys($badges));

    foreach ($added as $bid) {
      if (!key_exists($bid, $badges)) {
        $success = (boolean) user_badges_user_add_badge($uid, $bid);
      }
    }

    // what are the removed badges?
    $removed = array_diff(array_keys($badges), $newbadges);

    foreach ($removed as $bid) {
      // and user has this badge
      if (key_exists($bid, $badges)) {
        $success = $success && (boolean) user_badges_user_remove_badge($uid, $bid);
      }
    }
    if ($success && !$quiet) {
      drupal_set_message(t('Badges saved.'));
    }
    elseif (!$quiet) {
      drupal_set_message(t('There was a problem saving badges to the database.'), 'error');
    }
  }
}

/**
 * Add a badge to user.
 *
 * @param $uid
 *   User ID.
 * @param $bid
 *   Badge ID.
 * @param $type
 *   Whether set as part of the role, or individually assigned ('user', 'role').
 *
 * @return unknown
 */
function user_badges_user_add_badge($uid, $bid, $type = NULL) {
  user_badges_user_remove_badge($uid, $bid, $type);
  return db_query('INSERT INTO {user_badges_user} (uid, bid, type) VALUES (%d, %d, \'%s\')', $uid, $bid, $type);
}

function user_badges_user_remove_badge($uid, $bid, $type = NULL) {
  if (is_null($type)) {
    return db_query('DELETE FROM {user_badges_user} WHERE uid=%d AND bid=%d', $uid, $bid);
  }
  else {
    return db_query('DELETE FROM {user_badges_user} WHERE uid=%d AND bid=%d AND type=\'%s\'', $uid, $bid, $type);
  }
}

function user_badges_settings_page($op = NULL, $bid = NULL) {
  switch ($op) {
    case 'edit':
      if (is_numeric($bid)) {
        $output = drupal_get_form('user_badges_edit_form', $bid);
      }
      break;

    case 'delete' :
      if (is_numeric($bid)) {
        $output = user_badges_delete($bid);
      }
      break;

    default:
      $badges = user_badges_get_badges('all');
      $header = array(t('Name'), t('Image'), t('Operations'));
      if (is_array($badges)) {
        foreach ($badges as $badge) {
          $tablerow[$badge->bid]['name'] = $badge->name;
          $tablerow[$badge->bid]['image'] = theme('image', $badge->image, $badge->image, $badge->image);
          $tablerow[$badge->bid]['ops'] = l(t('edit'), 'admin/user/user_badges/edit/'. $badge->bid) .' '. l(t('delete'), 'admin/user/user_badges/delete/'. $badge->bid);
        }
      }
      $output = theme('table', $header, $tablerow, array('style' => 'width:100%'));
      $output .= "<br/><br/>";
      $form[] = array(
        '#type' => 'fieldset',
        '#title' => t('Add another'),
      );
      //$output .= user_badges_edit_form();
      $output .= drupal_get_form('user_badges_edit_form');
      break;
  }

  return $output;
}

function user_badges_edit_form_submit($form, &$form_state) {
  $form_state['redirect'] = user_badges_save_badge($form_state['values']);
}

/**
 * Define a form to upload the badge images.
 */
function user_badges_images_form($form_state) {
  $form = array('#skip_duplicate_check' => TRUE);
  if (module_exists('upload')) {
    $form['new']['upload'] = array('#type' => 'file', '#title' => t('Upload image'), '#size' => 40);
    $form['new']['attach'] = array('#type' => 'submit', '#value' => t('Upload'));
  }
  else {
    drupal_set_message(t('Upload of images requires the upload module to be enabled.'), 'error');
  }

  $form['#attributes']['enctype'] = 'multipart/form-data';

  $selects = user_badges_image_selects();
  if (count($selects)) {
    $form['images'] = array('#tree' => TRUE);
    foreach ($selects as $imagepath => $imageimg) {
      $form['images'][$imagepath] = array(
        '#type' => 'checkbox',
        '#title' => $imageimg,
        '#return_value' => 1,
        '#default_value' => FALSE,
        '#description' => check_plain($imagepath),
      );
    }
    $form['delete_image'] = array(
      '#type' => 'submit',
      '#value' => t('Delete'),
    );
  }
  return $form;
}

/**
 * Validate the submission.
 *
 * Check whether:
 * Delete has been chosen AND a checkbox has been selected
 * OR
 * Upload has been chosen AND the file upload form is not empty.
 */
function user_badges_images_form_validate($form, &$form_state) {
  $op = $form_state['clicked_button']['#value'];
  if ($op == t('Upload')) {
    $dir = file_create_path('badges');
    $is_writable = file_check_directory($dir, 1);
    if ($is_writable) {
      if ($file = file_save_upload('upload', array(), $dir)) {
        if (!image_get_info($file->filepath)) {
          file_delete($file->filepath);
          form_set_error('upload', t('Uploaded image file does not appear to be a valid image file.  Please try again'));
        }
        else {
          user_badges_hold_temporary_file($file);
          $form_state['values']['file_image'] = $file;
        }
      }
      else {
        form_set_error('upload', t('Cannot save image.  Enter the path to an image and try again.'));
      }
    }
    else {
      form_set_error('upload', t('Cannot save image - directory not writable'));
    }
  }
  else if ($op == t('Delete')) {
    if (count(array_filter($form_state['values']['images'])) == 0) {
      form_set_error('images', t('Please select images to delete.'));
    }
  }
}

function user_badges_hold_temporary_file($file = NULL) {
  static $static_file;
  if (isset($file)) {
    $static_file = $file;
  }
  return $file;
}

function user_badges_images_form_submit($form, &$form_state) {
  $op = $form_state['clicked_button']['#value'];
  // Save uploaded files
  if ($op == t('Upload')) {
    $file = $form_state['values']['file_image'];
    file_set_status($file, FILE_STATUS_PERMANENT);
  }
  else if ($op == t('Delete')) {
    foreach ($form_state['values']['images'] as $path => $is_removed) {
      if ($is_removed) {
        $to_delete[] = $path;
      }
    }
    if (is_array($to_delete)) {
      user_badges_image_delete($to_delete);
    }
  }
}

function user_badges_image_delete($to_delete) {
  foreach ($to_delete as $path) {
    if (file_check_location($path, file_create_path('badges'))) {
      file_delete($path);
    }
  }
}

function user_badges_roles_form() {
  $roles = user_roles();
  $badges = user_badges_get_roles();
  $selects = array('' => 'inactive') + user_badges_get_badges('select');
  $form['roles'] = array('#tree' => TRUE);
  foreach ($roles as $rid => $role) {
    if ($rid != 1) { // no badges for the anonymous role
      $form['roles'][$rid] = array(
        '#type' => 'select',
        '#title' => $role,
        '#default_value' => isset($badges[$rid]) ? $badges[$rid] : '',
        '#options' => $selects,
      );
    }
  }
  $form[] = array(
    '#type' => 'submit',
    '#value' => t('Save Roles'),
  );
  return $form;
}

function user_badges_roles_form_submit($form, &$form_state) {
  user_badges_save_roles($form_state['values']['roles']);
}

/**
 * Return array of user badges where keys are badge ids (bid)
 *   and values are object containing badge info
 * if $uid is a user id, returns badges for that user
 * if $uid is 'all', returns all badges
 * if $uid is 'select', returns badges for form_select options
 *   returned values for 'select' are just badge names
 */
function user_badges_get_badges($uid) {
  static $badges, $past_uid;
  if (empty($past_uid) || $past_uid !== $uid) {
    $past_uid = $uid;
    $badges = array();
    if ($uid == 'all' || $uid == 'select') {
      $sql = db_query('SELECT b.bid, b.weight, b.name, b.image FROM {user_badges_badges} b ORDER BY b.weight, b.name');
    }
    else {
      $sql = db_query('SELECT DISTINCT b.bid, b.weight, b.name, b.image FROM {user_badges_badges} b INNER JOIN {user_badges_user} u ON b.bid = u.bid WHERE u.uid = %d ORDER BY b.weight, b.name', $uid);
    }
    while ($badge = db_fetch_object($sql)) {
      if ($uid == 'select') {
        $badges[$badge->bid] = $badge->name;
      }
      else {
        $badges[$badge->bid] = $badge;
      }
    }
  }

  return $badges;
}

/**
 * Return badge object for given badge id
 */
function user_badges_get_badge($bid) {
  return db_fetch_object(db_query('SELECT * FROM {user_badges_badges} WHERE bid = %d', $bid));
}

/**
 * Define the edit form for userbadges.
 */
function user_badges_edit_form($form_state, $bid = NULL) {
  if (is_numeric($bid)) {
    $edit = db_fetch_object(db_query('SELECT * FROM {user_badges_badges} WHERE bid = %d', $bid));
    if (is_numeric($edit->bid)) {
      $form['bid'] = array(
        '#type' => 'hidden',
        '#value' => $edit->bid,
      );
    }
  }
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#default_value' => isset($edit) ? $edit->name : '',
    '#size' => 40,
    '#maxlength' => 100,
    '#description' => t('Name for the badge. Will be displayed as tooltip when rolling over badge image.'),
    '#attributes' => NULL,
    '#required' => TRUE,
  );
  $selects = user_badges_image_selects();
  if (count($selects)) {
    $form['image'] = array(
      '#type' => 'radios',
      '#title' => t('Image'),
      '#default_value' => isset($edit) ? $edit->image : '',
      '#options' => $selects,
      '#description' => t('Select an image to associate with this badge. You can upload additional images on the <a href="@url">Images page</a>.', array('@url' => url("admin/user/user_badges/images"))),
    );
  }
  else {
    drupal_set_message('<strong>'. t('You have to <a href="@upload_link">upload badge images</a> first.', array('@upload_link' => url("admin/user/user_badges/images"))) .'</strong>', 'error');
  }
  $form['weight'] = array(
    '#type' => 'weight',
    '#title' => t('Weight'),
    '#default_value' => isset($edit) ? $edit->weight : '',
    '#delta' => 10,
    '#description' => t('Lighter weighted items float to the top of lists. Heavier items go to the bottom.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * Saves information about a badge into the database
 */
function user_badges_save_badge($edit) {
  $edit = (object)$edit;
  if (isset($edit->bid) && preg_match("/^[0-9]+$/D", $edit->bid)) {
    db_query('DELETE FROM {user_badges_badges} WHERE bid = %d', $edit->bid);
    $result = db_query("INSERT INTO {user_badges_badges} (bid, name, image, weight) VALUES (%d, '%s', '%s', %d)", $edit->bid, $edit->name, $edit->image, $edit->weight);
    drupal_set_message('Edited image');
  }
  else {
    $result = db_query("INSERT INTO {user_badges_badges} (name, image, weight) VALUES ('%s', '%s', %d)", $edit->name, $edit->image, $edit->weight);
    drupal_set_message('Inserted new image');
  }
  if ($result) {
    drupal_set_message(t('Badge %badgename saved.', array('%badgename' => $edit->name)));
  }
  else {
    drupal_set_message(t('There was a problem saving the badge information into the database.'));
  }
  return 'admin/user/user_badges';
}

function user_badges_delete_form($form_state, $bid) {
  if ($badge = user_badges_get_badge($bid)) {
    $form = array();
    $form['badge'] = array('#value' => theme('user_badge_group', array(theme('user_badge', $badge))));
    $form['bid'] = array('#type' => 'value', '#value' => $bid);
    return confirm_form($form, t('Are you sure you want to delete the badge %name?', array('%name' => $badge->name)), 'admin/user/user_badges');
  }
  form_set_error('', t('This badge does not exist.'));
}

function user_badges_delete_form_submit($form, &$form_state) {
  $bid = $form_state['values']['bid'];
  db_query("DELETE FROM {user_badges_badges} WHERE bid = %d", $bid);
  db_query("DELETE FROM {user_badges_user} WHERE bid = %d", $bid);
  db_query("DELETE FROM {user_badges_roles} WHERE bid = %d", $bid);
  drupal_set_message(t('Badge deleted.'));
  $form_state['redirect'] = 'admin/user/user_badges';
}

function user_badges_image_selects() {
  $selects = array();
  $dir = file_create_path('badges');
  $files = file_scan_directory($dir, '.*\.(gif|jpg|jpeg|png)', array('.', '..', 'CVS'), 0, FALSE);
  foreach ($files as $file) {
    $selects[$file->filename] = theme('image', $file->filename, $file->filename, $file->filename);
  }

  return $selects;
}

/**
 * Returns an array where keys are role ids (rid) and values are badge ids (bid)
 * These values are assigned on admin/user/user_badges/roles
 *
 * @param
 * $rid - if set, return only value for this role
 *
 * @return
 * a list of roles
 */
function user_badges_get_roles($rid = NULL) {
  $roles = array();
  if ($rid) {
    $sql = db_query('SELECT * FROM {user_badges_roles} WHERE rid = %d', $rid);
  }
  else {
    $sql = db_query('SELECT * FROM {user_badges_roles}');
  }
  while ($row = db_fetch_object($sql)) {
    $roles[$row->rid] = $row->bid;
  }

  return $roles;
}

/**
 * Save information about roles for user_badges (in settings)
 */
function user_badges_save_roles($roles) {
  if (is_array($roles)) {
    $success = TRUE;
    db_query('DELETE FROM {user_badges_roles}');
    db_query("DELETE FROM {user_badges_user} WHERE type='role'");
    foreach ($roles as $rid => $bid) {
      if ($bid) {
        $success = $success && db_query('INSERT INTO {user_badges_roles} (rid, bid) VALUES (%d, %d)', $rid, $bid);
        // Authenticated user, rid 2 has no entry in the users_role table
        if ($rid == 2) {
          $success = $success && db_query("INSERT INTO {user_badges_user} (uid, bid, type) (SELECT uid, %d, 'role' FROM {users} WHERE uid > 0)", $bid);
        }
        else {
          $success = $success && db_query("INSERT INTO {user_badges_user} (uid, bid, type) (SELECT uid, %d, 'role' FROM {users_roles} WHERE rid=%d)", $bid, $rid);
        }
      }
    }
    if ($success) {
      drupal_set_message(t('Roles saved.'));
    }
    else {
      drupal_set_message(t('There was a problem saving roles to the database'));
    }
  }
}

/**
 * Returns HTML representation of user badges for given uid
 *   @param $uid
 *     the user id
 *   @param $refresh (FALSE)
 *     when TRUE, refreshes the cache for $uid
 *   @return string
 *     html representation of userbadges
 */
function user_badges_for_uid($uid, $refresh = FALSE) {
  static $cache;
  if ($uid) {
    if (isset($cache[$uid]) && !$refresh) {
      return $cache[$uid];
    }
    else {
      $user_badges = user_badges_get_badges($uid);
        foreach ((array)$user_badges as $badge) {
        $badges[] = theme('user_badge', $badge);
      }
      $cache[$uid] = isset($badges) ? theme('user_badge_group', $badges) : '';
      return $cache[$uid];
    }
  }
}

/**
 * Returns HTML representation of user badges for given user
 * $array is array defining criteria for user_load()
 * most common use will be:
 *   user_badges_for_user(array('uid'=>123));
 */
function user_badges_for_user($array) {
  $account = user_load($array);
  foreach ((array)$account->badges as $badge) {
    $badges[] = theme('user_badge', $badge);
  }
  if ($badges) {
    return theme('user_badge_group', $badges);
  }
}

/**
 * Return html representation of a group of badges
 * $badgeimages is an array of badge image tags from theme_user_badge()
 */
function theme_user_badge_group($badgeimages) {
  if (!empty($badgeimages)) {
    return '<div class="user_badges">'. implode('', $badgeimages) .'</div>';
  }
}

/**
 * Return html representation of a badge image
 * (note: theme_image does the check_plaining)
 */
function theme_user_badge($badge) {
  return theme('image', $badge->image, $badge->name, $badge->name);
}

/**
 *  Implementation of hook_views_api().
 */
function user_badges_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
* Implementation of hook_action_info().
*/
function user_badges_action_info() {
  return array(
    'user_badges_add_badge_action' => array(
      'description' => t('Add badge'),
      'type' => 'user',
      'configurable' => TRUE,
      'hooks' => array(
        'any' => TRUE,
       ),
      ),
    'user_badges_remove_badge_action' => array(
      'description' => t('Remove badge'),
      'type' => 'user',
      'configurable' => TRUE,
      'hooks' => array(
        'any' => TRUE,
       ),
    ),
  );
}

/**
* Implementation of a Drupal action.
* Adds a badge to the current user.
*/
function user_badges_add_badge_action(&$account, $context = array()) {
  if (isset($account->uid)) {
    $uid = $account->uid;
  }
  elseif (isset($context['uid'])) {
    $uid = $context['uid'];
  }
  else {
    global $user;
    $uid = $user->uid;
  }
  $success = TRUE;
  $badges = user_badges_get_badges('all');

  foreach ($context['badges'] as $bid) {
    $success = (boolean) user_badges_user_add_badge($uid, $bid, 'uid');
    if ($success) {
      watchdog('action', 'Added user badge %badge to user %name.', array('%name' => check_plain($user->name), '%badge' => check_plain($badges[$bid]->name)));
    }
    else {
      watchdog('action', 'Unable to add user badge %badge to user %name.', array('%name' => check_plain($user->name), '%badge' => check_plain($badges[$bid]->name)), WATCHDOG_WARNING);
    }
  }
}

function user_badges_add_badge_action_form($context) {
  $form['badges'] = array('#tree' => TRUE);

  $badges = user_badges_get_badges('all');
  $context['badges'] = is_array($context['badges']) ? $context['badges'] : array();

  foreach ($badges as $badge) {
    $form['badges'][$badge->bid] = array(
      '#type' => 'checkbox',
      '#title' => theme('user_badge', $badge),
      '#return_value' => 1,
      '#default_value' => $context['badges'][$badge->bid],
      '#description' => check_plain($badge->name),
    );
  }

  return $form;
}

function user_badges_add_badge_action_submit($form, $form_state) {
  $badges = array();
  foreach ($form_state['values']['badges'] as $badge => $set) {
    if ($set) {
      $badges[$badge] = $badge;
    }
  }
  return array('badges' => $badges);
}

/**
* Implementation of a Drupal action.
* Removes a badge to the current user.
*/
function user_badges_remove_badge_action(&$account, $context = array()) {
  if (isset($account->uid)) {
    $uid = $account->uid;
  }
  elseif (isset($context['uid'])) {
    $uid = $context['uid'];
  }
  else {
    global $user;
    $uid = $user->uid;
  }
  $success = TRUE;
  $badges = user_badges_get_badges('all');

  foreach ($context['badges'] as $bid) {
    $success = (boolean) user_badges_user_remove_badge($uid, $bid, 'uid');
    if ($success) {
      watchdog('action', 'Removed user badge %badge to user %name.', array('%name' => check_plain($user->name), '%badge' => check_plain($badges[$bid]->name)));
    }
    else {
      watchdog('action', 'Unable to remove user badge %badge to user %name.', array('%name' => check_plain($user->name), '%badge' => check_plain($badges[$bid]->name)), WATCHDOG_WARNING);
    }
  }
}

function user_badges_remove_badge_action_form($context) {
  $form['badges'] = array('#tree' => TRUE);

  $badges = user_badges_get_badges('all');
  $context['badges'] = is_array($context['badges']) ? $context['badges'] : array();

  foreach ($badges as $badge) {
    $form['badges'][$badge->bid] = array(
      '#type' => 'checkbox',
      '#title' => theme('user_badge', $badge),
      '#return_value' => 1,
      '#default_value' => $context['badges'][$badge->bid],
      '#description' => check_plain($badge->name),
    );
  }

  return $form;
}

function user_badges_remove_badge_action_submit($form, $form_state) {
  $badges = array();
  foreach ($form_state['values']['badges'] as $badge => $set) {
    if ($set) {
      $badges[$badge] = $badge;
    }
  }
  return array('badges' => $badges);
}
